### ISSUE TITLE
how to avoid obstacles？

### ISSUE THREAD

**Issue by GuangtaoLyu** [korrawe/Diffusion-Noise-Optimization#4]
hello,
thank you for your great work.
How can i find some related papers and datasets about avoiding obstacles?  I only find some words in your paper. Can you share more details?

**Comment by korrawe** [comment]
We didn't use (and didn't have) any training data with obstacles for training. As our method does not require training a new model, we manually create random obstacles for testing, represented as signed distance functions. 
For simplicity, we only use sphere-shaped obstacles because creating a good SDF from an arbitrary scene scan is a challenge on its own.
